# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: RxLeanCloud Open Source Docs
title: RxLeanCloud Docs
email: beliveme@outlook.com
description: Docs
repository: RxLeanCloud/docs
facebook_username: wujun19890209
twitter_username:  freewing999
github_username:   wujun4code
stackoverflow_tag: rxleancloud
serverfault_tag:   leancloud
# support_url: https://www.parse.com/help
# apis:
#   osx: http://parseplatform.org/Parse-SDK-iOS-OSX/api/
#   android: http://parseplatform.org/Parse-SDK-Android/api/
#   js: http://parseplatform.org/Parse-SDK-JS/api/
#   php: http://parseplatform.org/parse-php-sdk/namespaces/Parse.html
#   dotnet: http://parseplatform.org/Parse-SDK-dotNET/api/

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data","hardwrap"]
exclude: [ Gemfile, Gemfile.lock, README.md, config.codekit, webpack.config.js, node_modules, npm-debug.log, package.json ]
sass:
    sass_dir: css

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-mermaid
whitelist:
  - jekyll-redirect-from
mermaid:
  src: 'node_modules/mermaid/dist/mermaid.js'
